# .github/workflows/ci.yml
name: Continuous Integration

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --no-root --only main

      - name: Lint code
        run: poetry run flake8 --ignore E501

      - name: Run tests
        run: poetry run pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.PA_SSH_KEY }}
      
      - name: Add PythonAnywhere to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ssh.pythonanywhere.com >> ~/.ssh/known_hosts

      - name: Copy files to PythonAnywhere
        run: |
          scp -r . vimal729@ssh.pythonanywhere.com:/home/vimal729/thiran-api/

      - name: Deploy on PythonAnywhere
        run: |
          ssh vimal729@ssh.pythonanywhere.com "cd /home/vimal729/thiran-api/ && poetry install --no-root --only main && nohup poetry run uvicorn main:app --host 0.0.0.0 --port 8000 &"
