name: Continuous Integration

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
    tags:
      - 'v*.*.*'  # Trigger on version tags for Docker build

jobs:
  checkout:
    runs-on: ubuntu-latest
    outputs:
      # Set output to pass to other jobs
      artifact_path: ${{ steps.upload-artifact.outputs.artifact-path }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Upload repository as artifact
        id: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: repo
          path: .

  build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Download repository artifact
        uses: actions/download-artifact@v3
        with:
          name: repo

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --no-root --only main

      - name: Lint code
        run: poetry run flake8 --ignore E501

      - name: Run tests
        run: poetry run pytest

  build-and-publish-docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download repository artifact
        uses: actions/download-artifact@v3
        with:
          name: repo

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          # Convert organization and repo names to lowercase
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/${REPO_NAME}/thiran-api:${{ github.sha }} .

      - name: Push Docker image
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker push ghcr.io/${REPO_NAME}/thiran-api:${{ github.sha }}

      - name: Tag Docker image with latest
        if: github.ref == 'refs/heads/main'
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker tag ghcr.io/${REPO_NAME}/thiran-api:${{ github.sha }} ghcr.io/${REPO_NAME}/thiran-api:latest
          docker push ghcr.io/${REPO_NAME}/thiran-api:latest

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Download repository artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: repo

  #     - name: Set up SSH
  #       uses: webfactory/ssh-agent@v0.5.3
  #       with:
  #         ssh-private-key: ${{ secrets.PA_SSH_KEY }}

  #     - name: Add PythonAnywhere to known hosts
  #       run: |
  #         mkdir -p ~/.ssh
  #         ssh-keyscan -H ssh.pythonanywhere.com >> ~/.ssh/known_hosts

  #     - name: Copy files to PythonAnywhere
  #       run: |
  #         scp -r . vimal729@ssh.pythonanywhere.com:/home/vimal729/thiran-api/

  #     - name: Deploy on PythonAnywhere
  #       run: |
  #         ssh vimal729@ssh.pythonanywhere.com "cd /home/vimal729/thiran-api/ && poetry install --no-root --only main && nohup poetry run uvicorn main:app --host 0.0.0.0 --port 8000 &"
